#version 430 core

struct sdfPoint {

  vec3 pos;
  float sdfVal;

}

layout(std430, binding = 0) buffer grid {
  sdfPoint sdf[];
};

uniform float t;

layout(local_size_x = 1);

float sdfSphere(vec3 p, float s) {
  return length(p) - s;
}

void main() {

  int gridIndex = gl_WorkGroupID.x * gl_NumWorkGroups.y * gl_NumWorkGroups.z
                + gl_WorkGroupID.y * gl_NumWorkGroups.z
                + gl_WorkGroupID.z;

  sdf[gridIndex].sdfVal = sdfSphere(sdf[gridIndex].pos, 3.0);
}