#version 430 core

struct hhVert {
  vec3 pos;
  float _pad0;

  vec3 norm;
  float _pad1;

  vec3 col;
  float _pad2;

  vec2 uv;

  int update;
  int posID;
};

layout(std430, binding = 0) buffer vertices {
  hhVert verts[];
};

layout(std430, binding = 1) buffer velocities {
  vec4 v[];
};

layout(local_size_x = 12) in;

void main() {

  if (gl_LocalInvocationID.x == 0) {

    uint selfID = gl_WorkGroupID.x 
                + gl_WorkGroupID.y * gl_NumWorkGroups.x
                + gl_WorkGroupID.z * gl_NumWorkGroups.x * gl_NumWorkGroups.y;


    const float dt = 0.002;
    const float vDampen = 0.99999;

    v[selfID] *= vDampen;

    verts[selfID].pos += vec3(v[selfID]) * dt;
    verts[selfID].col = vec3(length(vec3(v[selfID]))) * vec3(0.07, 0.0, 0.0); 
    verts[selfID].update = 1;

  }
}